[package]
name = "automation"
version = "0.1.0"
authors = ["Tim Guenther <4759569+TimGuenther@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
